## Исключение (#1)

1. Напишите функцию `abort()`, которая принимает параметр `String`
2. Создайте исключение `throw new Exception` и передайте в конструктор параметр `String`.
3. В функции `main()` вызовите функцию `abort()` с аргументом `"Stop!"` и используйте `try catch` для обработки результата.
3. Отобразите в консоли `"Exception: Stop!"` после обработки исключения.